<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Harness</AssemblyName>
    <RootNamespace>Glass</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../src/GameSettings.cs" />
  </ItemGroup>
</Project>
